### ISSUE TITLE
Compilation error with XE8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/MustangpeakEasyListView#15]
```
Hello
I get this compilation error with XE 8. Is there something wrong with the 
packages?

[dcc32 Fatal Error] MPCommonObjects.pas(2811): E2411 Unit EasyTaskPanelForm in 
package EasyListviewD22 refers to unit MPCommonObjects which is not found in 
any package.  Packaged units must refer only to packaged units

In the distribution are missing the dpk and res files for XE8. Only the 
Compilers.inc files have been updated!

Sincerely

Peter

```

Original issue reported on code.google.com by `Peter.St...@univie.ac.at` on 4 Jul 2015 at 8:30

Attachments:
- [EasyListviewD22D.dpk](https://storage.googleapis.com/google-code-attachments/mustangpeakeasylistview/issue-15/comment-0/EasyListviewD22D.dpk)
- [EasyListviewD22.dpk](https://storage.googleapis.com/google-code-attachments/mustangpeakeasylistview/issue-15/comment-0/EasyListviewD22.dpk)
- [EasyListviewD22.res](https://storage.googleapis.com/google-code-attachments/mustangpeakeasylistview/issue-15/comment-0/EasyListviewD22.res)
- [EasyListviewD22D.res](https://storage.googleapis.com/google-code-attachments/mustangpeakeasylistview/issue-15/comment-0/EasyListviewD22D.res)

**Comment by pyscripter** [comment]
Installation instructions added.
